name: Test Artifact

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - run: |
          mkdir -p path/to/artifact
          echo hello > path/to/artifact/world.txt
      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: path/to/artifact
