name: dump PR

on:
  pull_request:
    types: [synchronize]

jobs:
  dump:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.before }}
      # Diff the diffs https://stackoverflow.com/a/9302664/1480205
      - name: Dump PR
        run: |
          git fetch --no-auto-gc origin ${{ github.event.pull_request.base.sha }} ${{ github.event.after }}
          echo "Changes to PR"
          diff <(git log ${{ github.event.pull_request.base.sha }}..${{ github.event.after }} -p) <(git log ${{ github.event.pull_request.base.sha }}..${{ github.event.before }} -p)
          cat << "EOF"
          ${{ toJSON(github) }}
          EOF
          env
