name: dump

on: [push, pull_request]

jobs:
  dump:
    runs-on: ubuntu-18.04
    steps:
      - name: Dump
        run: |
          cat > /dev/null << "EOF"
          ${{ toJSON(github) }}
          EOF
          env
