name: dump PR

on:
  pull_request:
    types: [synchronize]

jobs:
  dump:
    runs-on: ubuntu-18.04
    steps:
      # Diff the diffs https://stackoverflow.com/a/9302664/1480205
      - name: Dump PR
        run: |
          echo "Changes to PR"
          compare_url=${{ github.repository.compare_url }}
          diff <(curl ${compare_url/{base}...{head}/${{ github.event.pull_request.base.sha }}..${{ github.event.after }}.diff}) <(curl ${compare_url/{base}...{head}/${{ github.event.pull_request.base.sha }}..${{ github.event.before }}.diff})
          echo "Dump github object"
          cat << "EOF"
          ${{ toJSON(github) }}
          EOF
          env
