name: testing

on: [push, pull_request, create]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Dump event
        run: |
          echo "${{ toJSON(github) }}"
      - name: Extract tag
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          git for-each-ref ${{ github.ref }} --format='%(contents)'
