name: testing

on:
  create:
    ref_type: tag

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Extract tag message
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: { message } } = await github.git.getTag({
              owner: context.payload.repository.owner.name,
              repo: context.payload.repository.name,
              tag_sha: context.payload.after
            });
            return message;
          #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      - name: Dump steps
        run: echo "${{ toJSON(steps) }}"
