name: testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Dump github
        run: echo "${{ toJSON(github) }}"
      - name: Script
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return github.git.getTag({
                owner: context.repository.owner.name,
                repo: context.repository.name,
                tag_sha: context.sha
            });
        #uses: rectalogic/notify-irc@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        #run: |
        #  git for-each-ref ${{ github.ref }} --format='%(contents)'
      - name: Dump step
        run: echo "${{ toJSON(steps) }}"
