name: testing

on: [push, pull_request, create]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Dump event
        run: |
          echo "${{ toJSON(github) }}"
      - name: Extract tag
        if: github.event_name == 'push' && github.event.ref_type == 'tag'
        run: |
          git for-each-ref ${{ github.event.ref }} --format='%(contents)'
