name: testing

on: [push, pull_request, create]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Test host
        run: |
          env
          ls $ANDROID_HOME
          find $ANDROID_HOME -name '*emu*'
          find $ANDROID_HOME -name '*manag*'
          #apt list --installed
