name: testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Notify tag
        #uses: rectalogic/notify-irc@v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          git for-each-ref ${{ github.ref }} --format='%(contents)'
      - name: Dump step
        run: echo "${{ toJSON(steps) }}"
