name: keyscan

on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: keyscan
        run: |
          mkdir -p ~/.ssh
          chmod go-rwx ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
